### ISSUE TITLE
ValueError: 486 is not a valid PaladinsQueue

### ISSUE THREAD

**Issue by EthanHicks1** [luissilva1044894/Pyrez#6]
When using the function `getMatchPlayerDetails()` the error `ValueError: 486 is not a valid PaladinsQueue` is thrown when trying to get the details of a ranked match. I know Paladins Guru still does not have ranked stats for this season which may mean that they changed the Paladins API number for ranked matches.

**Comment by luissilva1044894** [comment]
@EthanHicks1 Are you sure that you've the latest Github version? I've already updated this 20 days ago ([`Ranked Keyboard (KBM) Queue ID`](https://github.com/luissilva1044894/Pyrez/blob/51e94133ec0936062f6b3ed51738b2c643f4c979/pyrez/enumerations.py#L391)). Since I need to update the Queue / Champ Ids manually, I'm thinking to just remove it... But not sure about this

Use this line ``` -e git+https://github.com/luissilva1044894/pyrez.git@master#egg=pyrez ``` in ```requirements.txt``` file instead Pypi version, for now. 

I saw that you're coding a Discord Bot and I notice that you're accessing data directly from Json... This Wrapper / repo was thought to simplify this. For example, getPlayer() for Paladins API / Paladins Endpoint will return  [`PlayerPaladins`](https://github.com/luissilva1044894/Pyrez/blob/51e94133ec0936062f6b3ed51738b2c643f4c979/pyrez/models.py#L86) class, this class constains exactly the same data that you're currently accessing manually by Json.

Also, this Discord Bot is similar to my another repo ([`FlaskPyrezAPI`](https://github.com/luissilva1044894/FlaskPyrezAPI)), so maybe you can took a look into this. This is being used for a lot Twitch streamers.

That's why I know that this isn't an issue. You can check here: https://nonsocial.herokuapp.com/api/kda?player=bugzy&platform=pc&champion=imani

**Comment by EthanHicks1** [comment]
Ok. This is my first time using the requirements.txt since I am programming it in PyCharm. I put that link in the reuirements.txt file and then did pip install -r requirements.txt. 

Now I get the following error:

> raise InvalidArgumentException("Invalid player!")
> pyrez.exceptions.InvalidArgumentException: Invalid player!

so in the function calls like: 

> paladinsAPI.getChampionRanks(player_name)

 or 

> paladinsAPI.getPlayerStatus(player_name)

It seems like now whenever I call a function that has a player name as the argument it throws that error.
All these worked before I did the upgrade. There is a good chance I could have done the upgrade wrong.

**Comment by luissilva1044894** [comment]
This is about the Crossplay Changes... Basically, just ``` getPlayer() ``` supports playerName actually and everything else supports just playerId. You can read the whole post [here](https://podio.com/hirezstudioscom/smite-api-developer-collaboration/status/10051005).
```
ENDPOINTS NO LONGER SUPPORTING PLAYERNAME

We want to make the endpoints that currently support the overloaded [playerId or playerName] parameter only support [playerId].

This would affect the following 5 endpoints (SMITE & Paladins):

getPlayerStatus()
getGodRanks()
getMatchHistory()
getQueueStats()
getFriends()

Endpoint getPlayer() would continue to support either [playerId or PlayerName] with no modifications for PC.
```

<br/>So, instead playerName, you need to use playerId. You can see how get playerId for every platform here:
![PlayerId Endpoints](https://i.imgur.com/tEJKpMQ.jpg)

**Comment by EthanHicks1** [comment]
Alright, thanks. With the update today they disabled ranked so still can't test to see if it works yet. Imani works now though.
